#!/usr/bin/env ruby

bash_path = ENV['HOME'] + '/.bash_profile'
bash_file = File.read(bash_path)
color_alias = /alias\s*COLOR\s*=\s*"[^;]*/.match(bash_file)[0]
color_alias_path_with_file = /(?<=").+/.match(color_alias)[0]
full_path = color_alias_path_with_file[0,color_alias_path_with_file.length-8]

Dir.chdir("#{full_path}")
Dir["./app/**/*.rb"].each{|f| require f}
Dir["./lib/*.rb"].each{|f| require f}

active = ColorScheme.determine_active
if !active.nil?
    ColorScheme.activate(active.text_color,active.background_color,active.text_format,active.overwrite_prompt)
else
    BashFile.default
end