production:
    adapter: sqlite3
    database: db/terminal_color_capture_production.sqlite
    pool: 5
    timeout: 5000

test:
    adapter: sqlite3
    database: db/terminal_color_capture_test.sqlite
    pool: 5
    timeout: 5000